#undef PPDHasGainIn
#undef PPDHasHQ
#undef PPDHasLookahead
#undef PPDHasEditor
#undef PPDEqualLoudnessMix
#undef PPDFPSMeters
#undef PPDFPSKnobs
#undef PPDMetersUseRMS
#undef PPD_GainIn_Min
#undef PPD_GainIn_Max
#undef PPD_GainOut_Min
#undef PPD_GainOut_Max
#undef PPDHasUnityGain
#undef PPD_UnityGainDefault
#undef PPDFPSValueBubble
#undef PPDValueBubbleVisibleTimeMs
#undef ValueBubbleSizePercentage